var imagesLoader = require("./views/images").create()
  , tooltip = require("./views/tooltip").create()
  , links = require("./views/links").create()
  , column = require("./views/column").create()
  , posts = require("./views/posts").create()
  , tagFilters = require("./views/tagfilters").create()
  , scroll = require("./views/scroll").create()
