require("./views/images").create()
require("./views/tooltip").create()
require("./views/links").create()
require("./views/column").create()
require("./views/posts").create()
require("./views/tagfilters").create()
require("./views/scroll").create()
